# This is only if you're using the kind
# environment to test
## MinIO(R) Gateway configuration
gateway:
  enabled: true
  type: azure
  replicaCount: 4
  auth:
    azure:
      storageAccountName: "blairlake"
      storageAccountKey: "Ez1Dg2MimHZQZljNdVthSqGsqefdy9iEmq5LaArT71LJdBJasyTK6RgEpT7hFEAe4z3+uhlAORJqSAZoG0TXFA=="
extraEnv:
  - name: MINIO_ETCD_ENDPOINTS
    value: http://etcd-headless:2379
#image:
#  registry: k8scc01covidacr.azurecr.io
#  repository: minio/minio
#  tag: 6379f1af
ingress:
  enabled: false
  hostname: minio.local
